server:
  url:

client:
  url:

app:
  name:
  host:
  port:
  debug: true
  readTimeout: 10
  writeTimeout: 30
  whitelist:
    - http://localhost:3000
    - http://localhost:5050
    - http://127.0.0.1:5500
    - http://localhost:5173

database:
  username:
  password:
  host:
  port:
  name:
  debug: true
  poolSize: 30
  IdleConnTimeoutSeconds: 100
  maxConnAgeSeconds: 3600
  sslMode:
  timeZone:

log:
  level: "debug"

auth:
  verifyTokenExpirationMinutes: 10
  accessTokenExpirationMinutes: 60
  resetTokenExpirationMinutes: 10
  jwtSecret:
