server:
  port: "8044"

app:
  name: "social-platform"
  host: "localhost"
  port: 8044
  debug: true
  readTimeout: 10
  writeTimeout: 30
  whitelist:

database:
  url: "postgres://username:password@localhost:5432/social-platform?sslmode=disable"
  username: "username"
  password: "password"
  host: "localhost"
  port: "5432"
  name: "social-platform"
  debug: true
  poolSize: 30
  IdleConnTimeoutSeconds: 100
  maxConnAgeSeconds: 3600
  sslMode: "disable"
  timeZone: "Asia/Ho_Chi_Minh"
  replicasPostgreSQL:
    - username: ""
      password: ""
      host: ""
      port: "5432"
      name: "postgres"
      debug: true
      poolSize: 60
      idleConnTimeoutSeconds: 10
      maxConnAgeSeconds: 3600

log:
  level: "info"

auth:
  verifyTokenExpirationMinutes: 5

client:
  url: "http://localhost:3000"
